name: Deploy NestJS with Prisma and Redis to VPS using Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "📁 Creating project folder if it doesn't exist..."
            mkdir -p ~/fixoo
            cd ~/fixoo

            if [ ! -d "learning-managment-system/.git" ]; then
              echo "🚀 Cloning repository..."
              git clone https://github.com/DaminboevM/learning-managment-system.git
            else
              echo "📦 Pulling latest changes..."
              cd learning-managment-system
              git pull origin main
            fi

            cd ~/fixoo/learning-managment-system

            echo "👨‍🔧 Giving Docker permissions..."
            sudo usermod -aG docker $USER || true

            echo "🛑 Stopping containers..."
            sudo docker compose down || true

            echo "🔨 Building containers..."
            sudo docker compose build

            echo "🚀 Starting containers..."
            sudo docker compose up -d

            echo "✅ Deployment finished!"
